### ISSUE TITLE
Non standard ssh port not working

### ISSUE THREAD

**Issue by sladec** [codercom/sshcode#19]
Tried to specify a different port for ssh on my server  
`sshcode user@server.io:port` returns error
`sshcode user@server.io  --ssh-flags '-p xxxx' ` is ignored

How should it be done?

**Comment by nhooyr** [comment]
Unfortunately cannot be done at the moment.

**Comment by ammario** [comment]
@nhooyr why not?

**Comment by nhooyr** [comment]
I guess you culd do `sshcode --skipsync user@server.io -p 8443`. Only issue is it won't work with rsync.

Simplest solution would be for you to specify the port in your ~/.ssh/config.

**Comment by ammario** [comment]
rsync has a thing for passing ssh flags, should be a simple change.

**Comment by sladec** [comment]
Hi
Thanks for the quick update.
Any info on how to do this now?
I am still getting an error.
`

**Comment by nhooyr** [comment]
`sshcode --ssh-flags "-p 2222"`

**Comment by sladec** [comment]
Thanks
This is what I get
[image: image.png]

**Comment by nhooyr** [comment]
Sorry I can't see the image, it was embedded incorrectly.

**Comment by mogwai** [comment]
Example here

`./sshcode user@example.com --ssh-flags "-p 1234" /home/user/work`
