### ISSUE TITLE
Add data-dir and extensions-dir flag

### ISSUE THREAD

**Issue by foresthoffman** [codercom/sshcode#34]
It would make sense to also have `--extensions-dir` and `--user-data-dir` flags, since both of those are available on code-server.

https://github.com/codercom/code-server/blob/5f40ebb8457380aa1e9955302d9e41a6b042ef14/packages/server/src/cli.ts#L23-L24

**Comment by ammario** [comment]
Related #29

I think it's best to have these as environment variables.

**Comment by SscSPs** [comment]
I think env variables are good, but config file would be better, won't have to pass them everytime..
We can have both, env variables having more priority than config. And config having more priority than defaults

**Comment by foresthoffman** [comment]
Environment variables can be easily placed in a user's `.bashrc` or `.bash_profile`.

**Comment by SscSPs** [comment]
My reason for having a different config file is that other apps should not accidently use those variables. I know this is rare, but possible. 
Noone will be going in some other application's configs accidently

**Comment by ammario** [comment]
It's not worth worrying about the chance of another application using an environment variable as specific as `VSCODE_SETTINGS_DIR`
