### ISSUE TITLE
Make releases executable

### ISSUE THREAD

**Issue by nol166** [codercom/sshcode#41]
At least on Mac, it requires `chmod +x` to run

**Comment by ammario** [comment]
AFAIK browsers have no support for specifying file permissions for downloads.

**Comment by nhooyr** [comment]
We should distribute a tar.

**Comment by ammario** [comment]
Is the tar extract better than the `chmod +x` ?

**Comment by nhooyr** [comment]
Its more automated. E.g. on macOS, I can just click the icon and it auto extracts it for me with the right perms on it. Don't have to think about it or get confused when I can't execute it.

Its just more obvious how to get it to work.

**Comment by ammario** [comment]
That's fair. On Linux I'm in the terminal no matter what. I'll get a tar release going.
