### ISSUE TITLE
Ctrl + keybindings won't work if no text is selected

### ISSUE THREAD

**Issue by Belval** [codercom/sshcode#42]
Lovely project, can't wait to integrate it into my day to day workflow, but I've hit a reasonably major problem. The shortcuts I would consider important (Ctrl+X, Ctrl+C, and Ctrl+V) won't work if no text is selected.

Steps to reproduce:
    - Clean Ubuntu 18.04 install
    - Install Chrome & Git
    - Install sshcode
    - Run sshcode to Ubuntu 18.04 host
    - Ctrl + X not working , nor is Ctrl + C, Ctrl + V, etc..

With a clean VSCode install Ctrl + X will delete the line if nothing is highlighted, same thing for Ctrl + C, etc...

**Comment by ammario** [comment]
cc @kylecarbs

**Comment by ammario** [comment]
Thank you for the reproduction steps, @kylecarbs is working on fixing this.

**Comment by kylecarbs** [comment]
New release with the fix is out now. Running sshcode will automatically download the new release.

Here's a direct link if you're interested: https://github.com/codercom/code-server/releases/tag/1.939-vsc1.33.1

Thanks for the report!

**Comment by Belval** [comment]
When I tested on my side this does not seem to be fixed.

Same machine, same set up, and I get the same behavior.

Also it crashes after a few seconds with this error message:

```
WARN  stderr {"data":"(node:9963) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n"}
Error: ENOENT: no such file or directory, open '/home/travis/build/codercom/code-server/packages/server/build/web/favicon.ico'
INFO  WebSocket opened / {"client":1,"ip":"127.0.0.1"}
INFO  Connected to shared process
internal/child_process.js:366
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at Object.spawn [as _spawn] (child_process.js:538:9)
    at t.async (/home/travis/build/codercom/code-server/packages/server/out/cli.js:504:34598)
    at e.exports (/home/travis/build/codercom/code-server/packages/server/out/cli.js:504:34099)
    at e (/home/travis/build/codercom/code-server/packages/server/out/cli.js:504:32722)
    at Timeout.u [as _onTimeout] (/home/travis/build/codercom/code-server/packages/server/out/cli.js:504:33015)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**Comment by kylecarbs** [comment]
Hm. What version does code-server output? Just to ensure you're on the latest version.

That error indicates you're out of memory. Is that the case?

**Comment by Belval** [comment]
The server is indeed feeble at 2GB of RAM, my bad! I'll try with another one.

**Comment by Belval** [comment]
Version is indeed `code-server v1.903-vsc1.33.1` which is not the one you said to use.

I did use sshcode to connect though, and you said it would update automatically.

**Comment by kylecarbs** [comment]
Found the issue. Binary in our public bucket wasn't updated.

Should be good to go now!
