### ISSUE TITLE
arm architecture ?

### ISSUE THREAD

**Issue by rican13** [codercom/sshcode#47]
Hello,
Can you adapt the code to work on a remote ARM machine ? 
For example, for : Odroid ARMBIAN 5.38 (Ubuntu 16.04.6 LTS)
Currently we have the following error message:
_bash: / tmp / codessh-code-server: can not execute binary file: Exec format error_
Thank you in advance.

**Comment by coadler** [comment]
We're tracking ARM support over on the `code-server` repo. See: https://github.com/codercom/code-server/issues/35
