### ISSUE TITLE
zsh: command not found: sshcode

### ISSUE THREAD

**Issue by calvinxli** [codercom/sshcode#62]
I'm getting "zsh: command not found: sshcode" when running sshcode user@ip from my Mac.
I installed go and ran "go get -u go.coder.com/sshcode" before this.

Are there any additional steps I may need to get this working?

**Comment by ajose01** [comment]
Probably a path issue in the script setup? 
```
~ ❯❯❯ /Users/angeljose/go/bin/sshcode
```
That's where it ends up.

**Comment by calvinxli** [comment]
added ~/go/bin to path and it worked!
